In [1]:
import pandas as pd

In [2]:
acs_filepath = '~/Projects/data/CLEAN_King_County_ACS_2019_tract.csv'
acs = pd.read_csv(acs_filepath)

In [3]:
acs.columns.values

array(['geoid', 'census_tract', 'median_age_total', 'estimate_total',
       'estimate_total_race', 'estimate_total_white',
       'estimate_total_africanamerican',
       'estimate_total_nativeamerican_or_alaskan_native',
       'estimate_total_asian',
       'estimate_total_nativehawaiian_and_pacific_islander',
       'estimate_total_other_race', 'estimate_total_two_or_more_races',
       'estimate_total_nativity_and_citizenship_status',
       'estimate_total_us_citizens_born_in_us',
       'estimate_total_us_citizens_in_pr_or_us_islands',
       'estimate_total_us_citizens_born_abroad_of_american_parents',
       'estimate_total_us_citizen_by_naturalization',
       'estimate_total_not_a_us_citizen', 'estimate_total_native_total',
       'estimate_total_foreign_born', 'estimate_total_speak_only_english',
       'estimate_total_speak_spanish',
       'estimate_spanish_speak_english_very_well',
       'estimate_spanish_speak_english_less_than_very_well',
       'estimate_total_speak_other_languages',
       'estimate_other_languages_english_less_than_very_weel',
       'estimate_total_never_married',
       'estimate_total_now_married_except_separated',
       'estimate_total_divorced', 'estimate_total_separated',
       'estimate_total_widowed', 'estimate_total_less_than_hs',
       'estimate_total_high_school_graduate',
       'estimate_total_some_college', "estimate_total_bachelor's_degree",
       'estimate_total_graduate_or_professional_degree', 'total',
       'less_than_10000', '10000_to_14999', '15000_to_19999',
       '20000_to_24999', '25000_to_29999', '30000_to_34999',
       '35000_to_39999', '40000_to_44999', '45000_to_49999',
       '50000_to_59999', '60000_to_74999', '75000_to_99999',
       '100000_to_124999', '125000_to_149999', '150000_to_199999',
       '200000_or_more', 'estimate_total_median_income_past_12mnths',
       'estimate_total_below_100_percent_of_the_poverty_level',
       'estimate_total_100_to_149_percent_of_poverty_level',
       'estimate_total_at_or_above_150_percent_of_poverty_level',
       'estimate_total_same_house_1_year_ago',
       'estimate_total_moved_within_same_county',
       'estimate_total_management_business_science_and_arts_occupations',
       'estimate_total_service_occupations',
       'estimate_total_sales_and_office_occupations',
       'estimate_total_natural_resources_construction_and_maintenance_occupations',
       'estimate_total_military',
       'agriculture_forestry_fishing_and_hunting_and_mining',
       'construction', 'manufacturing', 'wholesale_trade', 'retail_trade',
       'transportation_and_warehousing_and_utilities', 'information',
       'finance_and_insurance_and_real_estate_and_rental_and_leasing',
       'professional_scientific_and_management_and_administrative_and_waste_management_services',
       'educational_services_and_health_care_and_social_assistance',
       'arts_entertainment_and_recreation_and_accommodation_and_food_services',
       'other_services_except_public_administration',
       'public_administration', 'armed_forces',
       'householder_lived_in_owner_occupied_housing_units',
       'householder_lived_in_renter_occupied_housing_units', 'total.1',
       'less_than_5_minutes', '5_to_9_minutes', '10_to_14_minutes',
       '15_to_19_minutes', '20_to_24_minutes', '25_to_29_minutes',
       '30_to_34_minutes', '35_to_39_minutes', '40_to_44_minutes',
       '45_to_59_minutes', '60_to_89_minutes', '90_or_more_minutes',
       'total.2', 'family_households',
       'family_households_2_person_household',
       'family_households_3_person_household',
       'family_households_4_person_household',
       'family_households_5_person_household',
       'family_households_6_person_household',
       'family_households_7_or_more_person_household',
       'nonfamily_households', 'nonfamily_households_1_person_household',
       'nonfamily_households_2_person_household',
       'nonfamily_households_3_person_household',
       'nonfamily_households_4_person_household',
       'nonfamily_households_5_person_household',
       'nonfamily_households_6_person_household',
       'nonfamily_households_7_or_more_person_household', 'total.3',
       'enrolled_in_school',
       'enrolled_in_school_enrolled_in_nursery_school_preschool',
       'enrolled_in_school_enrolled_in_kindergarten',
       'enrolled_in_school_enrolled_in_grade_1_to_grade_4',
       'enrolled_in_school_enrolled_in_grade_5_to_grade_8',
       'enrolled_in_school_enrolled_in_grade_9_to_grade_12',
       'enrolled_in_school_enrolled_in_college_undergraduate_years',
       'enrolled_in_school_graduate_or_professional_school',
       'not_enrolled_in_school',
       'aggregate_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_wage_or_salary_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_self_employment_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_interest_dividends_or_net_rental_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_social_security_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_supplemental_security_income_ssi_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_public_assistance_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_retirement_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'aggregate_other_types_of_income_in_the_past_12_months_in_2010_inflation_adjusted_dollars',
       'gini_index', 'occupied', 'vacant', 'total.4', 'owner_occupied',
       'renter_occupied', 'for_rent', 'rented_not_occupied',
       'for_sale_only', 'sold_not_occupied',
       'for_seasonal_recreational_or_occasional_use',
       'for_migrant_workers', 'other_vacant',
       'median_year_structure_built', 'aggregate_rent_asked',
       'median_contract_rent', 'estimate_median_household_income',
       'median_monthly_housing_costs', 'total.5',
       'living_in_household_with_supplemental_security_income_ssi_cash_public_assistance_income_or_food'],
      dtype=object)

In [4]:
acs = acs.set_index('geoid')

In [5]:
income_column_names = ['less_than_10000', '10000_to_14999', '15000_to_19999',
       '20000_to_24999', '25000_to_29999', '30000_to_34999',
       '35000_to_39999', '40000_to_44999', '45000_to_49999',
       '50000_to_59999', '60000_to_74999', '75000_to_99999',
       '100000_to_124999', '125000_to_149999', '150000_to_199999',
       '200000_or_more']

In [6]:
acs = acs[income_column_names]

The poverty level is $12,880. 80\% of the federal poverty level is 10,304. Let's look at the people below yearly 10,000 income.

In [7]:
acs['Total']= acs[income_column_names].sum(axis=1)
acs['pct_below_80pct_povertyline'] = acs['less_than_10000'] / acs['Total']
acs[['pct_below_80pct_povertyline']].to_csv('geoid_high_poverty.csv')

In [14]:
acs.loc[53033032321, :]

less_than_10000                  54.000000
10000_to_14999                    0.000000
15000_to_19999                    9.000000
20000_to_24999                    0.000000
25000_to_29999                   18.000000
30000_to_34999                   14.000000
35000_to_39999                   14.000000
40000_to_44999                   31.000000
45000_to_49999                   20.000000
50000_to_59999                   41.000000
60000_to_74999                   87.000000
75000_to_99999                   40.000000
100000_to_124999                146.000000
125000_to_149999                118.000000
150000_to_199999                378.000000
200000_or_more                 1111.000000
Total                          2081.000000
pct_below_80pct_povertyline       0.025949
Name: 53033032321, dtype: float64

In [8]:
acs_upper_bound = pd.DataFrame(index=acs.index)
for i in range(16):
    acs_upper_bound[acs.columns[i]] = acs.iloc[:,0:i].sum(axis=1)
    
acs_upper_bound['Total'] = acs['Total']

for i in range(16):
    acs_upper_bound.iloc[:,i] -= acs_upper_bound['Total'] / 2
    
acs_upper_bound = acs_upper_bound.T
acs_upper_bound.columns = acs_upper_bound.columns.astype(str)
acs_upper_bound = acs_upper_bound.drop('Total')
acs_upper_bound

geoid,53033020700,53033020800,53033020900,53033021000,53033022001,53033020500,53033021400,53033022003,53033022300,53033031604,...,53033009900,53033010200,53033010500,53033011101,53033011700,53033020100,53033029204,53033029305,53033030003,53033030202
less_than_10000,-790.5,-874.0,-665.0,-1085.0,-1190.0,-1412.0,-705.0,-955.0,-507.5,-911.0,...,-1542.5,-1013.0,-2416.5,-992.5,-864.5,-649.5,-1272.5,-661.5,-1235.5,-1291.5
10000_to_14999,-705.5,-809.0,-640.0,-1050.0,-1162.0,-1218.0,-688.0,-926.0,-499.5,-891.0,...,-1421.5,-939.0,-2138.5,-887.5,-790.5,-629.5,-1186.5,-661.5,-1162.5,-1222.5
15000_to_19999,-672.5,-760.0,-540.0,-1018.0,-1068.0,-1184.0,-680.0,-926.0,-483.5,-880.0,...,-1393.5,-917.0,-2120.5,-777.5,-722.5,-629.5,-1169.5,-653.5,-1162.5,-1107.5
20000_to_24999,-582.5,-737.0,-485.0,-934.0,-1054.0,-1061.0,-671.0,-907.0,-475.5,-880.0,...,-1307.5,-899.0,-1993.5,-674.5,-693.5,-610.5,-1080.5,-638.5,-1058.5,-963.5
25000_to_29999,-520.5,-673.0,-439.0,-920.0,-1027.0,-986.0,-671.0,-891.0,-466.5,-862.0,...,-1198.5,-890.0,-1890.5,-643.5,-627.5,-610.5,-1025.5,-583.5,-1008.5,-897.5
30000_to_34999,-505.5,-627.0,-418.0,-889.0,-974.0,-832.0,-662.0,-851.0,-466.5,-824.0,...,-1142.5,-834.0,-1654.5,-602.5,-580.5,-587.5,-874.5,-541.5,-888.5,-804.5
35000_to_39999,-479.5,-627.0,-414.0,-870.0,-863.0,-747.0,-628.0,-844.0,-457.5,-813.0,...,-1099.5,-776.0,-1505.5,-524.5,-494.5,-528.5,-788.5,-529.5,-786.5,-679.5
40000_to_44999,-451.5,-590.0,-385.0,-733.0,-825.0,-617.0,-601.0,-801.0,-452.5,-767.0,...,-921.5,-765.0,-1375.5,-300.5,-437.5,-507.5,-757.5,-517.5,-647.5,-557.5
45000_to_49999,-426.5,-533.0,-355.0,-694.0,-811.0,-545.0,-518.0,-775.0,-438.5,-747.0,...,-818.5,-694.0,-1232.5,-245.5,-384.5,-461.5,-623.5,-476.5,-491.5,-448.5
50000_to_59999,-401.5,-522.0,-347.0,-540.0,-696.0,-443.0,-502.0,-708.0,-412.5,-693.0,...,-752.5,-604.0,-1221.5,-146.5,-324.5,-425.5,-506.5,-431.5,-447.5,-393.5
60000_to_74999,-278.5,-471.0,-222.0,-458.0,-594.0,-279.0,-474.0,-636.0,-399.5,-605.0,...,-441.5,-504.0,-969.5,75.5,-225.5,-370.5,-407.5,-320.5,-295.5,-152.5
75000_to_99999,-100.5,-371.0,-126.0,-301.0,-334.0,-99.0,-368.0,-467.0,-348.5,-443.0,...,-217.5,-322.0,-644.5,223.5,-113.5,-257.5,6.5,-210.5,106.5,237.5
100000_to_124999,142.5,-176.0,-10.0,46.0,-30.0,345.0,-207.0,-215.0,-262.5,-25.0,...,211.5,-105.0,54.5,483.5,205.5,-82.5,327.5,-28.5,538.5,660.5
125000_to_149999,351.5,62.0,147.0,345.0,168.0,689.0,-70.0,132.0,-199.5,233.0,...,631.5,110.0,539.5,638.5,328.5,91.5,541.5,166.5,843.5,831.5
150000_to_199999,469.5,230.0,257.0,569.0,384.0,898.0,130.0,468.0,-102.5,488.0,...,903.5,264.0,996.5,693.5,523.5,225.5,822.5,279.5,1079.5,1056.5
200000_or_more,659.5,532.0,450.0,886.0,709.0,1138.0,333.0,774.0,46.5,692.0,...,1173.5,596.0,1608.5,901.5,729.5,396.5,1085.5,534.5,1168.5,1248.5

In [9]:
def find_median(geoid):
    """find median given categories in the indices"""
    
    # return only positive counts for that column
    min_df = acs_upper_bound[acs_upper_bound[geoid] > 0]
    # return the name of the smallest category
    
    print(geoid)
    print(list(min_df[min_df[geoid] == min_df[geoid].min()].index)[0])
    
    return list(min_df[min_df[geoid] == min_df[geoid].min()].index)[0]

all_geoid = list(acs_upper_bound.columns)
all_geoid.remove('53033990100')
all_geoid.remove('53033024200')
all_geoid.remove('53033024602')

# set 53033990100 as NaN because there are no people in that category

for geo_id in all_geoid:
    find_median(geo_id)

53033020700
100000_to_124999
53033020800
125000_to_149999
53033020900
125000_to_149999
53033021000
100000_to_124999
53033022001
125000_to_149999
53033020500
100000_to_124999
53033021400
150000_to_199999
53033022003
125000_to_149999
53033022300
200000_or_more
53033031604
125000_to_149999
53033031706
100000_to_124999
53033032011
125000_to_149999
53033032213
200000_or_more
53033032214
200000_or_more
53033002600
125000_to_149999
53033004500
125000_to_149999
53033004700
100000_to_124999
53033005100
125000_to_149999
53033006700
125000_to_149999
53033010100
125000_to_149999
53033010900
75000_to_99999
53033011102
100000_to_124999
53033032500
125000_to_149999
53033000401
35000_to_39999
53033001300
75000_to_99999
53033001500
150000_to_199999
53033002100
125000_to_149999
53033003600
100000_to_124999
53033003800
125000_to_149999
53033006100
125000_to_149999
53033032602
200000_or_more
53033032703
125000_to_149999
53033000600
100000_to_124999
53033026300
75000_to_99999
53033027800
125000_to_149999
53033028000
60000_to_74999
53033011401
100000_to_124999
53033011402
60000_to_74999
53033023403
150000_to_199999
53033023404
200000_or_more
53033023803
125000_to_149999
53033023804
125000_to_149999
53033025005
125000_to_149999
53033025006
200000_or_more
53033025301
100000_to_124999
53033025302
60000_to_74999
53033025601
75000_to_99999
53033025602
125000_to_149999
53033025805
75000_to_99999
53033025806
100000_to_124999
53033029101
75000_to_99999
53033029102
100000_to_124999
53033029205
75000_to_99999
53033029206
35000_to_39999
53033030005
75000_to_99999
53033030006
50000_to_59999
53033031705
125000_to_149999
53033032010
125000_to_149999
53033030313
50000_to_59999
53033030314
40000_to_44999
53033031605
125000_to_149999
53033030305
75000_to_99999
53033030503
60000_to_74999
53033030504
75000_to_99999
53033030801
60000_to_74999
53033031204
125000_to_149999
53033031904
125000_to_149999
53033032008
125000_to_149999
53033032207
200000_or_more
53033032210
150000_to_199999
53033032003
125000_to_149999
53033032007
125000_to_149999
53033032311
150000_to_199999
53033011500
125000_to_149999
53033011600
125000_to_149999
53033020600
100000_to_124999
53033021700
100000_to_124999
53033021803
100000_to_124999
53033021906
125000_to_149999
53033007300
100000_to_124999
53033007600
100000_to_124999
53033007900
100000_to_124999
53033009200
25000_to_29999
53033012000
125000_to_149999
53033021100
100000_to_124999
53033021904
125000_to_149999
53033021905
100000_to_124999
53033022701
150000_to_199999
53033023201
100000_to_124999
53033024300
125000_to_149999
53033032401
150000_to_199999
53033028802
75000_to_99999
53033029304
100000_to_124999
53033030100
100000_to_124999
53033030304
75000_to_99999
53033030600
75000_to_99999
53033030802
60000_to_74999
53033031000
125000_to_149999
53033031800
125000_to_149999
53033030310
100000_to_124999
53033031100
75000_to_99999
53033031202
100000_to_124999
53033031908
100000_to_124999
53033000500
150000_to_199999
53033000900
150000_to_199999
53033001100
100000_to_124999
53033002800
150000_to_199999
53033002900
125000_to_149999
53033003100
150000_to_199999
53033003900
125000_to_149999
53033004200
150000_to_199999
53033004600
150000_to_199999
53033006000
125000_to_149999
53033006300
150000_to_199999
53033007700
125000_to_149999
53033008300
75000_to_99999
53033008900
125000_to_149999
53033009100
45000_to_49999
53033009400
75000_to_99999
53033032307
200000_or_more
53033032005
125000_to_149999
53033032203
200000_or_more
53033032208
125000_to_149999
53033024800
100000_to_124999
53033024903
200000_or_more
53033025003
200000_or_more
53033025200
100000_to_124999
53033026100
60000_to_74999
53033026700
125000_to_149999
53033027300
75000_to_99999
53033027600
100000_to_124999
53033029405
100000_to_124999
53033029602
150000_to_199999
53033029901
100000_to_124999
53033030306
100000_to_124999
53033030308
100000_to_124999
53033030309
75000_to_99999
53033030403
100000_to_124999
53033029203
60000_to_74999
53033029502
100000_to_124999
53033029504
50000_to_59999
53033030700
60000_to_74999
53033030902
60000_to_74999
53033031301
100000_to_124999
53033031501
100000_to_124999
53033031502
100000_to_124999
53033031906
125000_to_149999
53033031909
125000_to_149999
53033032212
150000_to_199999
53033032316
200000_or_more
53033032320
200000_or_more
53033032702
125000_to_149999
53033032322
200000_or_more
53033032704
125000_to_149999
53033031206
100000_to_124999
53033030201
75000_to_99999
53033030401
100000_to_124999
53033031205
75000_to_99999
53033031601
125000_to_149999
53033029306
125000_to_149999
53033029408
60000_to_74999
53033029601
75000_to_99999
53033022400
150000_to_199999
53033022500
150000_to_199999
53033023801
125000_to_149999
53033024000
150000_to_199999
53033025001
150000_to_199999
53033025102
125000_to_149999
53033025804
100000_to_124999
53033026802
60000_to_74999
53033028100
75000_to_99999
53033028700
100000_to_124999
53033028902
60000_to_74999
53033029004
45000_to_49999
53033032315
200000_or_more
53033002700
150000_to_199999
53033004100
200000_or_more
53033004900
125000_to_149999
53033005000
100000_to_124999
53033005302
20000_to_24999
53033006800
150000_to_199999
53033007100
100000_to_124999
53033007200
125000_to_149999
53033008500
75000_to_99999
53033008700
100000_to_124999
53033010300
100000_to_124999
53033010600
125000_to_149999
53033012100
150000_to_199999
53033032006
125000_to_149999
53033032104
125000_to_149999
53033032317
200000_or_more
53033032325
125000_to_149999
53033032309
125000_to_149999
53033031704
125000_to_149999
53033032313
125000_to_149999
53033032319
100000_to_124999
53033032321

IndexError: list index out of range

In [ ]:
min_df = acs_upper_bound[acs_upper_bound['53033990100'] > 0]
min_df

In [ ]:
"""1 2
2 2
3 2
4 2
5 2

1 2
2 4
3 6
4 8
5 10

1 -3
2 -1
3 1
4 3
5 5"""

In [ ]:
"""1 2
2 3
3 5
4 2
5 2

1 2
2 5
3 10
4 12
5 14

1 -5
2 -2
3 3
4 5
5 -6.5"""

In [ ]:
acs_upper_bound

another way i can do it is to make frequencies of each category, convert the category as a number, and let the describe() do the job by itself